version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
    networks:
      - postgres-network
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@example.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - /var/lib/pgadmin/

networks: 
  postgres-network:
    driver: bridge